project:
  type: website
  output-dir: docs

website:
  title: "Kristopher Huang's Portfolio Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: my-skills.qmd
        text: My Skills
      - href: general-marketing.qmd
        text: General Marketing
      - href: projects.qmd
        text: My Projects
      - href: my-resume.qmd
        text: My Résumé

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

