---
title: "General Marketing"
body-classes: general-marketing
---

I've chosen my future role in a marketing career to be in **General Marketing**. Below details how and why I came to the decision.

------------------------------------------------------------------------

# My Initial Choice

Before I became interested in Marketing, my initial choice was Computer Engineering. I figured that I could use the skills I gained to work with my own computers at home, such as fixing problems or improving their performance. However, I feel that a career in this field isn't viable for me for a couple of reasons:

-   Programming can be **complicated** and **frustrating** for me sometimes. The last thing I want to happen is to get stuck trying to solve a coding problem while on a tight schedule and getting frustrated at being unable to figure out what to do.
-   A **lot** of programming is involved. I'm okay with doing a bit of it once in a while, but working a job that involves doing it constantly is overwhelming.
-   There are just so many functions and arguments to memorize. Without a complete guide or AI, I would have no idea what to do with certain assignments.

I also thought about getting into video game development since I like playing video games in my spare time, but standard coding is already complicated enough and doing it for video games is whole new can of worms, so I decided against it.

***

# The Business Administration Major Classes

While taking the required classes for my Business Administration Major, I formed an opinion on the options based on my experiences in the classes. The classes I liked the least are **Accounting**, **Technology and Operations Management**, and **Finance, Real Estate, and Law**. The reason is due to one thing the classes have in common: **Highly Complicated Word Problems**.

While I'm fine with doing math equations, word problems are what really make my head hurt and cause my frustration to surface. They can contain irrelevant information, word things in a way that confuses you, and ask you to create and solve equations from what mish-mash of information you are given instead of having something simple and straightforward. The reason I'm able to pass these classes is because I have the foresight to take detailed notes for my assignments and exams.

On the other hand, I find that **Management and Human Resources**, **Economics**, and **International Business and Marketing** are more lax in comparison. MHR and IBM have group presentations, which I'm fine with doing as long as everyone pulls their weight, and EC's math problems are simpler and not overly complicated.

***

# Interest in Marketing

My interest in the Marketing option started growing when I took **IBM 3012 - Principles of Marketing Management**. Several topics caught my interest, such as **brand imagery**, **sensory marketing**, **marketing mediums**, **social media marketing**, and **importing and exporting**. My interest increased further when I started taking more courses for the IBM option in the Fall 2025 Semester. It got to the point where I started using AI to research more about marketing topics and scenarios. As for the type of Marketing I chose, I went with **General Marketing** because **it's the most well-rounded of the choices**. I'm a person who prefers balanced choices over specialized ones because I like to be able to do a bit of everything and help out in different fields. For example, at a job, I can work in advertising, but if the social media marketing team needs some help, I can lend a hand.