---
title: "My Skills"
body-classes: my-skills
---

I've always been told that I'm a smart person with a high IQ that's capable of doing anything if I put my mind to it, and I'd like to believe that in order to maintain a positive self-image of myself. This page details the skills I possess that can be useful in a casual or job setting.

***

# Creativity

I've always had an active and wide imagination, always thinking of scenarios in my head, such as **a fictional adventure for a character**, **creating scenes and interactions in sandbox video games like Garry's Mod**, and **thinking of my own concepts for things that interest me**, such as **futuristic mechanical tools that can be used to make jobs easier**. I often get inspiration from works of others, such as written stories and artworks.

I can come up with solutions to different problems depending on the scenario and the tools I'm given to work with. An example is **using an old skateboard as a trolley to move heavy objects around at home**. In a working environment, I would have to ask others, especially a higher-up, for their thoughts in order to avoid jumping the gun and getting in trouble. I think I would thrive in a job that requires me to use my creativity to come up with concepts and designs, such as a **concept artist**.

***

# Fast Learner

I often find myself learning about something fairly quick, sometimes through correct assumptions based on what I'm shown. For example, in a new video game, **I can figure out the controls, mechanics, and gimmicks within a couple of minutes from just testing things out**.

If I'm given **specific instructions** on how to do something, I will be able to follow along. Once I do that task enough, I'll be able to remember it. An example is **math**, **one of the subjects I've often been told I'm good at**. I've grown so accustomed to certain mathematical concepts, that **if you show me an equation**, **I'll be able to figure out the order of operations and which variables produce what values**.

In a work setting, I'll be willing to learn as much as I can about my job through **listening to what I'm told**, **doing the task until I get the hang of it**, and **asking questions for specific situations**. Once I get the gist of everything, I can handle things without too much issue.

***

# Organization

I'm a firm believer that **organization being one of the most important traits a person should possess**. Without it, we would be scrambling helplessly, unable to find what we're looking for through an unkempt mess.

When it comes to the work I do, I always categorize them and keep things consistent. For example, for my classes, I always create a folder for each one to store things related to them. Then I create subfolders for different types of things in that class, such as homework assignments and project elements.

My need for organization even extends to minor things. For example, if I come across a book on a shelf that fell over or is in the wrong place, I'll take a few seconds to straighten it out.

***

# Dedication

Getting things done before a deadline is critical. Not only does it ensure you have time to look things over for mistakes, but it shows that you are serious about giving your best effort, and it nets you some spare time to rest and enjoy yourself after doing some hard work. **"All work and no play makes Jack a dull boy"** after all. Completing all of my tasks early removes a massive weight from my chest.

In school, I always made it a priority to **get my schoolwork done so I don't have to worry about it later**. It gives me time to both relax and study if there's a test coming up.

I've been taught to **"take the initiative"** whenever I can. It essentially means that I should do what needs to be done without being told. An example is that if I notice a mess in a workspace, I should clean it up instead of waiting for someone to tell me to. It shows that I'm committed to working hard and understand what I'm supposed to do.

***

# Team Player

Teamwork is important when it comes to tasks that require multiple participants to get done. While I may not be leader material, **I'm always willing to give my all on whatever part I'm given**. I'm willing to communicate, coordinate, listen to feedback, and take one for the team when a situation calls for it.

On the other hand, I do have worries when it comes to being a team player, namely teammates not doing their parts and slacking behind and coming off as nagging or pushy if I communicate too fervently. I want to make sure that **everyone is on the same page** and that the working environment for everyone is **positive**, **hassle-free**, and **flexible**.